CREATE TABLE CARD_BANK(
ID_CARD NUMBER(10) PRIMARY KEY,
NUMBER_PAN NUMBER(19) UNIQUE NOT NULL,
NAME VARCHAR2(256) NOT NULL,
DOCUMENT_NUMBER VARCHAR2(15),
TYPE_CARD NUMBER(1,0) NOT NULL,
CELL_PHONE VARCHAR2(10) NOT NULL,
STATUS_CARD NUMBER(1,0) DEFAULT 0 NOT NULL,
TOKEN_CARD NUMBER(2) NOT NULL
)


CREATE SEQUENCE CARD_BANK_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999 NOCYCLE CACHE 20 NOORDER;

CREATE TRIGGER "CARD_BANK_TRG" 
BEFORE INSERT ON CARD_BANK
FOR EACH ROW 
BEGIN 
	SELECT CARD_BANK_SEQ.nextval
	INTO :NEW.ID_CARD
	FROM dual;
END;
